using System.Xml.Serialization;


namespace Libraries.enums
{

    public enum TraitTypes
    {

        [XmlEnum("ArmorBuilding")] ArmorBuilding = 63,
        [XmlEnum("ArmorCloth")] ArmorCloth = 64,
        [XmlEnum("ArmorLgt")] ArmorLgt = 65,
        [XmlEnum("ArmorMed")] ArmorMed = 66,
        [XmlEnum("ArmorPlt")] ArmorPlt = 67,
        [XmlEnum("Arrows")] Arrows = 68,
        [XmlEnum("BallistaArms")] BallistaArms = 69,
        [XmlEnum("BellyBows")] BellyBows = 70,
        [XmlEnum("Bows")] Bows = 71,
        [XmlEnum("FireThrowers")] FireThrowers = 72,
        [XmlEnum("FishingNet")] FishingNet = 73,
        [XmlEnum("Gear")] Gear = 74,
        [XmlEnum("GearBldg")] GearBldg = 75,
        [XmlEnum("GearBoat")] GearBoat = 76,
        [XmlEnum("GearVill")] GearVill = 77,
        [XmlEnum("GearPriest")] GearPriest = 78,
        [XmlEnum("GearSiege")] GearSiege = 79,
        [XmlEnum("Javalins")] Javalins = 80,
        [XmlEnum("Merchant")] Merchant = 81,
        [XmlEnum("RamHeads")] RamHeads = 82,
        [XmlEnum("Spears1H")] Spears1H = 83,
        [XmlEnum("Spears2H")] Spears2H = 84,
        [XmlEnum("Staffs2H")] Staffs2H = 85,
        [XmlEnum("Shields")] Shields = 86,
        [XmlEnum("Swords1H")] Swords1H = 87,
        [XmlEnum("Tools")] Tools = 88,
        [XmlEnum("Clubs2H")] Clubs2H = 89,
        [XmlEnum("ScoutSpecial1H")] ScoutSpecial1H = 90,
        [XmlEnum("GreatAxe")] GreatAxe = 91,
        [XmlEnum("Sling")] Sling = 93,
        [XmlEnum("Scepter")] Scepter = 92,
        [XmlEnum("Torc")] Torc = 133,
        [XmlEnum("Warpaint")] Warpaint = 138,
        [XmlEnum("War Horn")] WarHorn = 134,
        [XmlEnum("VanityShield")] VanityShield = 142,
        [XmlEnum("VanityWeapon")] VanityWeapon = 140,
        [XmlEnum("VanityHelm")] VanityHelm = 141,

        [XmlEnum("ConCommonCav")] ConCommonCav = 95,
        [XmlEnum("ConUncommonCav")] ConUncommonCav = 96,
        [XmlEnum("ConRareCav")] ConRareCav = 97,
        [XmlEnum("ConEpicCav")] ConEpicCav = 98,
        [XmlEnum("ConCommonBldg")] ConCommonBldg = 99,
        [XmlEnum("ConUncommonBldg")] ConUncommonBldg = 100,
        [XmlEnum("ConRareBldg")] ConRareBldg = 101,
        [XmlEnum("ConEpicBldg")] ConEpicBldg = 102,
        [XmlEnum("ConCommonArc")] ConCommonArc = 103,
        [XmlEnum("ConUncommonArc")] ConUncommonArc = 104,
        [XmlEnum("ConRareArc")] ConRareArc = 105,
        [XmlEnum("ConEpicArc")] ConEpicArc = 106,
        [XmlEnum("ConCommonSie")] ConCommonSie = 107,
        [XmlEnum("ConUncommonSie")] ConUncommonSie = 108,
        [XmlEnum("ConRareSie")] ConRareSie = 109,
        [XmlEnum("ConEpicSie")] ConEpicSie = 110,
        [XmlEnum("ConCommonInf")] ConCommonInf = 111,
        [XmlEnum("ConUncommonInf")] ConUncommonInf = 112,
        [XmlEnum("ConRareInf")] ConRareInf = 113,
        [XmlEnum("ConEpicInf")] ConEpicInf = 114,
        [XmlEnum("ConCommonRes")] ConCommonRes = 115,
        [XmlEnum("ConUncommonRes")] ConUncommonRes = 116,
        [XmlEnum("ConRareRes")] ConRareRes = 117,
        [XmlEnum("ConEpicRes")] ConEpicRes = 118,
        [XmlEnum("ConCommonPriest")] ConCommonPriest = 119,
        [XmlEnum("ConUncommonPriest")] ConUncommonPriest = 120,
        [XmlEnum("ConRarePriest")] ConRarePriest = 121,
        [XmlEnum("ConEpicPriest")] ConEpicPriest = 122,
        [XmlEnum("ConUncommonShip")] ConUncommonShip = 124,
        [XmlEnum("ConRareShip")] ConRareShip = 125,
        [XmlEnum("ConEpicShip")] ConEpicShip = 126,
        [XmlEnum("ConCommonShip")] ConCommonShip = 127,       

    }

}
